ansible_user: ec2-user
ansible_password: DevOps321
MONGODB_HOST: mongodb-"{{ env }}".pugasaha.online
CATALOGUE_HOST: catalogue-"{{ env }}".pugasaha.online
REDIS_HOST: redis-"{{ env }}".pugasaha.online
USER_HOST: user-"{{ env }}".pugasaha.online
CART_HOST: cart-"{{ env }}".pugasaha.online
MYSQL_HOST: mysql-"{{ env }}".pugasaha.online
SHIPPING_HOST: shipping-"{{ env }}".pugasaha.online
RABBITMQ_HOST: rabbitmq-"{{ env }}".pugasaha.online
PAYMENT_HOST: payment-"{{ env }}".pugasaha.online